### ISSUE TITLE
An error occured while running the 'ColorAdjustmentScript.m' script

### ISSUE THREAD

**Issue by ghost** [junyanz/RealismCNN#1]
Hi there.
I tried running your code, and found that an error occured due to line 69 of 'ColorAdjustmentScript.m'.
which says
ims{3} = fullfile(outImgFold, [name ext '.png'])

I wonder if there's a writing mistake? The 'ext' variable was not defined in the script.
Thanks.

**Comment by junyanz** [comment]
Hi, it's a typo. I just fixed it.
